favicon = "images/itsme.png"
preloader = false
search = false
mainSections = ["blog"]
related_post = true
image_gallery = true
contact_form_action = "#"
google_tag_manager = ""
custom_script = ""
theme_copyright = true
copyright = "©️ 2026 Terell Davis "
[[social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/Terell-Davis"
[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/terell-davis-19a21026a"
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"
[valine_comment]
enable = true
appId = ""
appKey = ""
avatar = ""
pageSize = 10
visitor = true
highlight = true
recordIP = true
enableQQ = false
[metadata]
keywords = ["Hydrogen","Hugo","Themefisher","GetHugoThemes","Statichunt"]
description = "This is meta description"
author = "Statichunt"
image = "images/developer.png"
[matomo]
enable = false
url = ""
id = ""
[baidu]
enable = false
analytics_id = ""
[plausible]
enable = false
domain = ""
[counter]
enable = false
username = ""
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
